/**
 * Agent 1A — Page maps for Grade 8 Integrated Science (CBC / KICD).
 * Each topic: 20 distinct non-overlapping pages, foundational → advanced.
 */

export const PAGE_MAPS = {
  '1.1': {
    topicName: 'Elements and Compounds',
    strand: 'Strand 1: Mixtures, Elements and Compounds',
    subStrand: '1.1 Elements and Compounds',
    pages: [
      { title: 'Matter and Pure Substances', scope: 'Define matter; pure substances vs mixtures', keywords: /matter|pure substance|mixture|homogeneous|heterogeneous/i },
      { title: 'What Is an Element', scope: 'Element definition and building-block role', keywords: /element|cannot be broken|building block/i },
      { title: 'Atoms as Building Units', scope: 'Atom as smallest unit of an element', keywords: /atom|smallest particle|chemically identical/i },
      { title: 'What Is a Compound', scope: 'Compound formation and fixed proportions', keywords: /compound|chemically combine|fixed proportion|ratio/i },
      { title: 'Elements Versus Compounds', scope: 'Clear comparison without overlap with later symbols work', keywords: /difference|element|compound|broken down/i },
      { title: 'Rules for Writing Chemical Symbols', scope: 'Capitalization and universal use of symbols', keywords: /symbol|capital|lowercase|universal/i },
      { title: 'Symbols from English Names', scope: 'H C N O F He Ca Cl Al Mg and similar', keywords: /hydrogen|carbon|nitrogen|oxygen|helium|english/i },
      { title: 'Symbols from Latin Names', scope: 'Na K Fe Cu Ag Au Pb Hg and Latin roots', keywords: /latin|natrium|kalium|ferrum|cuprum|aurum/i },
      { title: 'Chemical Formulas of Compounds', scope: 'How formulas show elements and ratios', keywords: /formula|H2O|NaCl|ratio/i },
      { title: 'Water as a Compound', scope: 'H₂O composition and properties link', keywords: /water|hydrogen|oxygen|H2O/i },
      { title: 'Common Salt as a Compound', scope: 'NaCl, Lake Magadi and kitchen use', keywords: /salt|sodium|chlorine|NaCl|Magadi/i },
      { title: 'Carbon Hydrogen and Oxygen in Foods', scope: 'CHO in staples ugali rice potatoes', keywords: /carbon|hydrogen|oxygen|carbohydrate|food/i },
      { title: 'Nitrogen and Body Proteins', scope: 'N in meat beans milk eggs', keywords: /nitrogen|protein|amino|beans/i },
      { title: 'Calcium for Bones and Teeth', scope: 'Ca sources including sukuma wiki and milk', keywords: /calcium|bones|teeth|milk|sukuma/i },
      { title: 'Iron and Healthy Blood', scope: 'Fe hemoglobin liver beans spinach', keywords: /iron|blood|hemoglobin|liver|spinach/i },
      { title: 'Fluoride and Tooth Protection', scope: 'F/fluoride in toothpaste tea fish', keywords: /fluor|tooth|enamel|toothpaste/i },
      { title: 'Useful Metals Gold and Silver', scope: 'Au Ag properties and uses', keywords: /gold|silver|jewellery|tarnish/i },
      { title: 'Iron Steel and Everyday Tools', scope: 'Fe steel jembe construction', keywords: /iron|steel|construction|tool|jembe/i },
      { title: 'Reading Packaging Labels', scope: 'Elements and compounds named on labels', keywords: /packaging|label|toothpaste|bottled water|ingredient/i },
      { title: 'Topic Synthesis and Exam Practice', scope: 'Integrated assessment across 1.1 only new stems', keywords: /element|compound|symbol|formula/i },
    ],
  },
  '1.2': {
    topicName: 'Physical and chemical changes',
    strand: 'Strand 1: Mixtures, Elements and Compounds',
    subStrand: '1.2 Physical and Chemical Changes',
    pages: [
      { title: 'States of Matter Overview', scope: 'Solid liquid gas introduction', keywords: /states of matter|solid|liquid|gas/i },
      { title: 'Properties of Solids', scope: 'Shape volume packing compressibility', keywords: /solid|definite shape|packed/i },
      { title: 'Properties of Liquids', scope: 'Definite volume no definite shape', keywords: /liquid|no definite shape|container/i },
      { title: 'Properties of Gases', scope: 'No fixed shape or volume compressibility', keywords: /gas|compressible|fill/i },
      { title: 'Particle Arrangement Model', scope: 'Particle pictures for three states', keywords: /particle|intermolecular|vibrate|slide/i },
      { title: 'Density Across States', scope: 'Typical density order solids liquids gases', keywords: /density/i },
      { title: 'Pure Substances', scope: 'Fixed melting boiling behaviour', keywords: /pure|melting|boiling/i },
      { title: 'Impure Substances and Mixtures', scope: 'Mixtures change melting boiling points', keywords: /impure|mixture|impurit/i },
      { title: 'Physical Changes Defined', scope: 'No new substance; often reversible', keywords: /physical change|reversible|no new substance/i },
      { title: 'Melting Freezing and Evaporation', scope: 'Change of state examples as physical', keywords: /melting|freezing|evaporation|condensation/i },
      { title: 'Chemical Changes Defined', scope: 'New substances form; hard to reverse', keywords: /chemical change|new substance|irreversible/i },
      { title: 'Burning and Rusting', scope: 'Classic chemical change examples', keywords: /burning|rust|combustion|oxidation/i },
      { title: 'Baking Soda and Vinegar Reaction', scope: 'CO₂ production as chemical change', keywords: /baking soda|vinegar|carbon dioxide|reaction/i },
      { title: 'Comparing Physical and Chemical Changes', scope: 'Side-by-side criteria only', keywords: /physical|chemical|compare|difference/i },
      { title: 'Heat Effects on Matter', scope: 'Heating causing state or chemical change', keywords: /heat|temperature|heating/i },
      { title: 'Hydrated Salts Introduction', scope: 'Water of crystallisation idea if in notes', keywords: /hydrat|crystal|salt/i },
      { title: 'Daily Life Physical Changes', scope: 'Drying clothes ice making cooking steam', keywords: /drying|ice|steam|clothes/i },
      { title: 'Daily Life Chemical Changes', scope: 'Cooking food spoilage burning charcoal', keywords: /cooking|spoil|charcoal|burn/i },
      { title: 'Safety When Heating Substances', scope: 'Lab and kitchen heat safety', keywords: /safety|heat|burn|goggles/i },
      { title: 'Topic Synthesis Physical Chemical Changes', scope: 'Integrated exam practice new stems', keywords: /physical|chemical|state/i },
    ],
  },
  '1.3': {
    topicName: 'Classes of fire',
    strand: 'Strand 1: Mixtures, Elements and Compounds',
    subStrand: '1.3 Classes of Fire',
    pages: [
      { title: 'What Is Fire', scope: 'Combustion basics for Grade 8', keywords: /fire|combustion|burn/i },
      { title: 'The Fire Triangle', scope: 'Fuel heat oxygen', keywords: /fire triangle|fuel|heat|oxygen/i },
      { title: 'Removing Fuel from a Fire', scope: 'Starvation method', keywords: /fuel|remove|starve/i },
      { title: 'Removing Heat from a Fire', scope: 'Cooling method', keywords: /cool|heat|water/i },
      { title: 'Removing Oxygen from a Fire', scope: 'Smothering method', keywords: /oxygen|smother|cover/i },
      { title: 'Class A Fires', scope: 'Ordinary combustibles wood paper cloth', keywords: /class A|wood|paper|cloth/i },
      { title: 'Class B Fires', scope: 'Flammable liquids petrol oils', keywords: /class B|petrol|oil|liquid/i },
      { title: 'Class C Fires', scope: 'Electrical equipment fires', keywords: /class C|electrical|electric/i },
      { title: 'Class D and Special Fires', scope: 'Metals and other special cases if noted', keywords: /class D|metal|special/i },
      { title: 'Why Water Is Not Universal', scope: 'Water unsafe on petrol and electrical fires', keywords: /water|petrol|electrical|unsuitable/i },
      { title: 'Types of Extinguishers', scope: 'Match extinguisher to class', keywords: /extinguisher|foam|CO2|dry powder/i },
      { title: 'Using a Fire Blanket', scope: 'Smothering small fires safely', keywords: /blanket|smother|pan/i },
      { title: 'School Fire Safety Rules', scope: 'Alarm evacuate assembly point', keywords: /school|alarm|evacuate|assembly/i },
      { title: 'Home Kitchen Fire Safety', scope: 'Cooking oil and stove precautions', keywords: /kitchen|cooking|stove|oil/i },
      { title: 'First Actions When You See Smoke', scope: 'Raise alarm get help do not fight large fires', keywords: /smoke|alarm|help|first/i },
      { title: 'Fire Escape Planning', scope: 'Routes and drills', keywords: /escape|exit|drill|route/i },
      { title: 'Fire Safety Equipment Survey', scope: 'Identify equipment at school/home', keywords: /equipment|extinguisher|hose|bucket/i },
      { title: 'Case Study Market Stall Fire', scope: 'Apply classes and triangle to a stall scenario', keywords: /market|stall|class|triangle/i },
      { title: 'Case Study Electrical Socket Fire', scope: 'Class C response without water', keywords: /socket|electrical|class C/i },
      { title: 'Topic Synthesis Fire Safety', scope: 'Integrated assessment new stems', keywords: /fire|class|extinguisher|triangle/i },
    ],
  },
  '2.1': {
    topicName: 'The Cell',
    strand: 'Strand 2: Living Things and Their Environment',
    subStrand: '2.1 The Cell',
    pages: [
      { title: 'Cells as Units of Life', scope: 'Cell theory intro for Grade 8', keywords: /cell|unit of life|living/i },
      { title: 'The Light Microscope Parts', scope: 'Eyepiece objective stage mirror/lamp', keywords: /microscope|eyepiece|objective|stage/i },
      { title: 'Handling a Microscope Safely', scope: 'Carry focus lighting rules', keywords: /microscope|handle|focus|care/i },
      { title: 'Preparing a Simple Slide', scope: 'Specimen cover slip basics', keywords: /slide|cover|specimen|mount/i },
      { title: 'Plant Cell Structures', scope: 'Wall membrane nucleus cytoplasm chloroplast vacuole', keywords: /plant cell|cell wall|chloroplast|vacuole/i },
      { title: 'Animal Cell Structures', scope: 'Membrane nucleus cytoplasm', keywords: /animal cell|membrane|nucleus|cytoplasm/i },
      { title: 'Comparing Plant and Animal Cells', scope: 'Similarities and differences', keywords: /compare|plant|animal|difference|similar/i },
      { title: 'Cell Wall Versus Cell Membrane', scope: 'Roles of each boundary', keywords: /cell wall|cell membrane|boundary/i },
      { title: 'Nucleus and Control of the Cell', scope: 'Nucleus role', keywords: /nucleus|control|genetic/i },
      { title: 'Cytoplasm and Organelles Overview', scope: 'Site of many cell activities', keywords: /cytoplasm|organelle/i },
      { title: 'Chloroplasts and Photosynthesis Link', scope: 'Why green plants need chloroplasts', keywords: /chloroplast|photosynthesis|green/i },
      { title: 'Vacuoles in Plant Cells', scope: 'Storage and support roles', keywords: /vacuole|sap|turgor/i },
      { title: 'Magnification Formula', scope: 'Eyepiece × objective', keywords: /magnification|eyepiece|objective|total/i },
      { title: 'Calculating Magnification', scope: 'Worked numerical examples', keywords: /magnification|calculate|×|x10|x40/i },
      { title: 'Estimating Size Under Microscope', scope: 'Field of view idea if in notes', keywords: /size|field|estimate|diameter/i },
      { title: 'Observing Onion Epidermis', scope: 'Classic plant cell practical', keywords: /onion|epidermis|plant/i },
      { title: 'Observing Cheek Cells', scope: 'Classic animal cell practical safety', keywords: /cheek|animal|swab/i },
      { title: 'Drawing Biological Diagrams', scope: 'Clear labelled drawings rules', keywords: /diagram|label|draw/i },
      { title: 'Cells Tissues and Organisms Link', scope: 'Levels of organisation brief', keywords: /tissue|organ|organism|organisation/i },
      { title: 'Topic Synthesis The Cell', scope: 'Integrated exam practice', keywords: /cell|microscope|magnification/i },
    ],
  },
  '2.2': {
    topicName: 'Movement of Materials in and out of the cell',
    strand: 'Strand 2: Living Things and Their Environment',
    subStrand: '2.2 Movement of Materials',
    pages: [
      { title: 'Why Materials Move in Cells', scope: 'Need for uptake and removal', keywords: /movement|material|cell|transport/i },
      { title: 'Solutes Solvents and Solutions', scope: 'Definitions with sugar/salt water', keywords: /solute|solvent|solution/i },
      { title: 'Concentrated and Dilute Solutions', scope: 'Relative amounts of solute', keywords: /concentrated|dilute|concentration/i },
      { title: 'The Cell Membrane as a Barrier', scope: 'Selectively permeable idea', keywords: /membrane|selectively permeable|barrier/i },
      { title: 'Diffusion Defined', scope: 'High to low concentration', keywords: /diffusion|high concentr|low concentr/i },
      { title: 'Diffusion in Liquids Experiment', scope: 'Ink or dye in water', keywords: /ink|dye|beaker|diffusion/i },
      { title: 'Diffusion in Gases', scope: 'Perfume or cooking smell', keywords: /perfume|gas|smell|diffusion/i },
      { title: 'Factors Affecting Diffusion', scope: 'Temperature distance concentration gradient', keywords: /temperature|faster|gradient|distance/i },
      { title: 'Roles of Diffusion in Living Things', scope: 'Gas exchange nutrient movement overview', keywords: /role of diffusion|living|oxygen|carbon dioxide/i },
      { title: 'Osmosis Defined', scope: 'Water across selectively permeable membrane', keywords: /osmosis|water|selectively permeable/i },
      { title: 'Visking Tubing Model of Osmosis', scope: 'Sugar solution experiment', keywords: /visking|tubing|sugar|osmosis/i },
      { title: 'Osmosis in Plant Root Hairs', scope: 'Water uptake from soil', keywords: /root hair|soil|plant|osmosis/i },
      { title: 'Turgor and Wilting in Plants', scope: 'Support from water in cells', keywords: /turgor|wilt|flaccid|plant/i },
      { title: 'Osmosis in Animal Cells', scope: 'Swelling and shrinking risks', keywords: /animal|red blood|swell|shrink/i },
      { title: 'Comparing Diffusion and Osmosis', scope: 'Two clear differences', keywords: /compare|diffusion|osmosis/i },
      { title: 'Everyday Diffusion Examples', scope: 'Market smells tea sugar dissolving links', keywords: /everyday|market|tea|smell/i },
      { title: 'Everyday Osmosis Examples', scope: 'Soaking beans limp vegetables', keywords: /soak|bean|vegetable|wilt/i },
      { title: 'Experimental Fair Testing', scope: 'Controls variables in diffusion/osmosis labs', keywords: /experiment|control|variable|fair/i },
      { title: 'Health and Safety in Cell Transport Labs', scope: 'Glass chemicals hygiene', keywords: /safety|glass|hygiene|lab/i },
      { title: 'Topic Synthesis Diffusion and Osmosis', scope: 'Integrated exam practice', keywords: /diffusion|osmosis|solution/i },
    ],
  },
  '2.3': {
    topicName: 'Reproduction in human beings',
    strand: 'Strand 2: Living Things and Their Environment',
    subStrand: '2.3 Reproduction in Human Beings',
    pages: [
      { title: 'Why Reproduction Matters', scope: 'Continuity of human life age-appropriate', keywords: /reproduction|species|life/i },
      { title: 'Hormones as Chemical Messengers', scope: 'Hormone control overview', keywords: /hormone|chemical messenger/i },
      { title: 'Overview of the Menstrual Cycle', scope: 'Approx 28–35 days purpose', keywords: /menstrual cycle|28|35|month/i },
      { title: 'Stages of the Menstrual Cycle', scope: 'Key events by approximate days', keywords: /day|menstruation|ovulation|uterus/i },
      { title: 'Menstruation Explained', scope: 'Monthly period scientific terms', keywords: /menstruation|period|blood flow/i },
      { title: 'Ovulation Explained', scope: 'Release of ovum', keywords: /ovulation|ovum|oviduct/i },
      { title: 'Challenges Related to Menstruation', scope: 'Cramps irregular cycles myths vs facts', keywords: /challenge|cramp|irregular|myth/i },
      { title: 'Managing Menstrual Challenges', scope: 'Hygiene rest warmth clinic help', keywords: /management|warm bath|doctor|hygiene/i },
      { title: 'Male Reproductive Structures Overview', scope: 'Age-appropriate organ names from notes', keywords: /male|sperm|testis|penis/i },
      { title: 'Female Reproductive Structures Overview', scope: 'Age-appropriate organ names from notes', keywords: /female|ovary|uterus|oviduct|vagina/i },
      { title: 'Sperm and Ovum', scope: 'Gametes roles', keywords: /sperm|ovum|gamete/i },
      { title: 'Fertilization', scope: 'One sperm joins ovum', keywords: /fertilization|fertilisation|penetrate/i },
      { title: 'Implantation', scope: 'Embryo settles in uterus', keywords: /implantation|uterus|embryo/i },
      { title: 'Pregnancy Care Basics', scope: 'Health seeking and respect', keywords: /pregnancy|care|clinic|antenatal/i },
      { title: 'Hygiene and Reproductive Health', scope: 'Daily hygiene dignity privacy', keywords: /hygiene|clean|sanitary|privacy/i },
      { title: 'Respect Consent and Values', scope: 'PCI values age-appropriate', keywords: /respect|value|consent|dignity/i },
      { title: 'Seeking Help from Trusted Adults', scope: 'Teacher parent clinician pathways', keywords: /help|doctor|trusted|adult|clinic/i },
      { title: 'Rejecting Myths with Science', scope: 'Evidence over rumour', keywords: /myth|rumour|science|fact/i },
      { title: 'Vocabulary Accuracy Matters', scope: 'Correct terms reduce stigma and error', keywords: /term|vocabulary|accurate/i },
      { title: 'Topic Synthesis Human Reproduction', scope: 'Integrated respectful exam practice', keywords: /menstrual|fertilization|hygiene|hormone/i },
    ],
  },
  '3.1': {
    topicName: 'Transformation of Energy',
    strand: 'Strand 3: Force and Energy',
    subStrand: '3.1 Transformation of Energy',
    pages: [
      { title: 'What Is Energy', scope: 'Ability to do work idea', keywords: /energy|work|ability/i },
      { title: 'Forms of Energy Overview', scope: 'List common forms', keywords: /form|chemical|electrical|kinetic|potential|light|heat|sound/i },
      { title: 'Chemical Energy', scope: 'Food dry cells fuels', keywords: /chemical energy|food|dry cell|fuel/i },
      { title: 'Electrical Energy', scope: 'Circuits appliances', keywords: /electrical|current|appliance/i },
      { title: 'Kinetic and Potential Energy', scope: 'Motion and stored position/state', keywords: /kinetic|potential|moving|stored/i },
      { title: 'Light Heat and Sound Energy', scope: 'Everyday examples', keywords: /light|heat|sound/i },
      { title: 'Energy Transformation Idea', scope: 'Energy changes form', keywords: /transformation|transformed|change form/i },
      { title: 'Torch Energy Chain', scope: 'Chemical → electrical → light heat', keywords: /torch|bulb|dry cell|chemical|electrical|light/i },
      { title: 'Solar Home Systems', scope: 'Light to electrical to useful forms', keywords: /solar|panel|sun|electrical/i },
      { title: 'Cooking Energy Changes', scope: 'Chemical/heat chains in kitchen', keywords: /cook|stove|heat|fuel/i },
      { title: 'Transport Energy Changes', scope: 'Boda boda matatu chemical to kinetic', keywords: /boda|vehicle|kinetic|fuel/i },
      { title: 'Conservation of Energy Idea', scope: 'Not destroyed; transformed', keywords: /conservation|destroyed|transformed/i },
      { title: 'Useful and Wasted Energy', scope: 'Heat losses noise', keywords: /wasted|useful|heat loss/i },
      { title: 'Electrical Safety at Home', scope: 'Cables sockets water overload', keywords: /safety|cable|socket|water|overload/i },
      { title: 'Safety with Heat and Flames', scope: 'Stoves charcoal jikos', keywords: /flame|jiko|charcoal|burn/i },
      { title: 'Energy Saving Habits', scope: 'Switch off efficient use', keywords: /save|switch off|efficient/i },
      { title: 'Tracing Energy in a Phone Charge', scope: 'Multi-step chain', keywords: /phone|charge|battery|electrical/i },
      { title: 'Tracing Energy in a Radio', scope: 'Chemical/electrical to sound', keywords: /radio|sound|electrical/i },
      { title: 'Local Renewable Energy Examples', scope: 'Solar biogas mini-hydro if relevant', keywords: /renewable|biogas|hydro|wind|solar/i },
      { title: 'Topic Synthesis Energy Transformations', scope: 'Integrated exam practice', keywords: /energy|transform|safety|form/i },
    ],
  },
  '3.2': {
    topicName: 'Pressure',
    strand: 'Strand 3: Force and Energy',
    subStrand: '3.2 Pressure',
    pages: [
      { title: 'Everyday Meaning of Pressure', scope: 'Force felt on an area', keywords: /pressure|force|area/i },
      { title: 'Scientific Definition of Pressure', scope: 'Force acting normally per unit area', keywords: /define|normally|perpendicular|unit area/i },
      { title: 'Factors Affecting Pressure', scope: 'Force and area relationship', keywords: /factor|force|area|increase|decrease/i },
      { title: 'Formula P Equals F Over A', scope: 'Symbols and SI units', keywords: /P =|formula|pascal|N\/m/i },
      { title: 'Worked Calculation Basic', scope: 'Numerical P = F/A example 1', keywords: /calculate|200|0.50|example/i },
      { title: 'Worked Calculation Rearranging', scope: 'Find F or A from P', keywords: /rearrange|find force|find area/i },
      { title: 'Pressure in Solids Applications Cutting', scope: 'Knives jembes sharp edges', keywords: /knife|jembe|sharp|cut/i },
      { title: 'Pressure in Solids Broad Bases', scope: 'Camel feet planks skis', keywords: /camel|broad|plank|ski|elephant/i },
      { title: 'School Bag Straps Example', scope: 'Wide vs narrow straps', keywords: /bag|strap|shoulder|pad/i },
      { title: 'Pressure in Liquids Depth', scope: 'Increases with depth', keywords: /liquid|depth|hρg|deeper/i },
      { title: 'Dam Walls Design', scope: 'Thicker at bottom', keywords: /dam|thicker|bottom|wall/i },
      { title: 'Elevated Water Tanks', scope: 'Height and supply pressure', keywords: /tank|elevated|water supply|height/i },
      { title: 'Atmospheric Pressure Idea', scope: 'Air pressure around us', keywords: /atmospheric|air pressure|atmosphere/i },
      { title: 'Football Boots and Studs', scope: 'Grip via smaller area', keywords: /stud|boot|grip|football/i },
      { title: 'Tractor and Soft Ground', scope: 'Wide tyres reduce sinking', keywords: /tractor|tyre|soft|mud|sink/i },
      { title: 'Safety and Pressure Hazards', scope: 'Sharp tools heavy loads', keywords: /safety|sharp|heavy|hazard/i },
      { title: 'Measuring Ideas Force and Area', scope: 'Estimating area for pressure problems', keywords: /measure|estimate|area|m2/i },
      { title: 'Mixed Word Problems', scope: 'New numerical contexts', keywords: /problem|word|calculate/i },
      { title: 'Pressure Myths Corrected', scope: 'Common learner errors', keywords: /myth|error|definite|liquid pressure/i },
      { title: 'Topic Synthesis Pressure', scope: 'Integrated exam practice', keywords: /pressure|force|area|liquid|solid/i },
    ],
  },
};

export function getPageMap(topicNumber) {
  return PAGE_MAPS[String(topicNumber)] || null;
}
